package models

import "time"

// BrandProfile defines the identity and voice of the company agent.
type BrandProfile struct {
	ID                    string   `json:"id" bson:"_id"`
	UserID                string   `json:"user_id" bson:"user_id"`
	Name                  string   `json:"name" bson:"name"`
	Industry              string   `json:"industry" bson:"industry"`
	Voice                 string   `json:"voice" bson:"voice"`
	TargetAudience        string   `json:"target_audience" bson:"target_audience"`
	Topics                []string `json:"topics" bson:"topics"`
	AntiTopics            []string `json:"anti_topics" bson:"anti_topics"`
	ScheduleIntervalHours int      `json:"schedule_interval_hours" bson:"schedule_interval_hours"`
}

// Trend represents a potential topic discovered during research.
type Trend struct {
	Query     string    `json:"query" bson:"query"`
	Title     string    `json:"title" bson:"title"`
	Snippet   string    `json:"snippet" bson:"snippet"`
	URL       string    `json:"url" bson:"url"`
	Timestamp time.Time `json:"timestamp" bson:"timestamp"`
}

// PostStatus defines the lifecycle of a post.
type PostStatus string

const (
	StatusDraft     PostStatus = "draft"
	StatusPending   PostStatus = "pending_review"
	StatusApproved  PostStatus = "approved"
	StatusScheduled PostStatus = "scheduled"
	StatusPublished PostStatus = "published"
	StatusFailed    PostStatus = "failed"
)

type ScheduledPost struct {
	ID          string     `json:"id" bson:"_id"`
	BrandID     string     `json:"brand_id" bson:"brand_id"`
	Topic       string     `json:"topic" bson:"topic"`
	Content     string     `json:"content" bson:"content"`
	Platform    string     `json:"platform" bson:"platform"`
	Status      PostStatus `json:"status" bson:"status"`
	ScheduledAt time.Time  `json:"scheduled_at" bson:"scheduled_at"`
	CreatedAt   time.Time  `json:"created_at" bson:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at" bson:"updated_at"`
}

// Post represents a piece of content generated by the agent.
type Post struct {
	ID        string     `json:"id" bson:"_id"`
	SocialID  string     `json:"social_id" bson:"social_id"`
	BrandID   string     `json:"brand_id" bson:"brand_id"`
	Topic     string     `json:"topic" bson:"topic"`
	Content   string     `json:"content" bson:"content"`
	Platform  string     `json:"platform" bson:"platform"`
	Status    PostStatus `json:"status" bson:"status"`
	Analytics Analytics  `json:"analytics" bson:"analytics"`
	CreatedAt time.Time  `json:"created_at" bson:"created_at"`
	UpdatedAt time.Time  `json:"updated_at" bson:"updated_at"`
}

// Analytics holds performance data for a post.
type Analytics struct {
	Views    int `json:"views" bson:"views"`
	Likes    int `json:"likes" bson:"likes"`
	Shares   int `json:"shares" bson:"shares"`
	Comments int `json:"comments" bson:"comments"`
}

// GlobalAnalytics holds aggregated data across all brands.
type GlobalAnalytics struct {
	TotalImpressions int `json:"total_impressions" bson:"total_impressions"`
	TotalLikes       int `json:"total_likes" bson:"total_likes"`
	TotalShares      int `json:"total_shares" bson:"total_shares"`
	TotalComments    int `json:"total_comments" bson:"total_comments"`
}

// BrandPerformance holds performance metrics for a specific brand.
type BrandPerformance struct {
	BrandID   string  `json:"brand_id" bson:"brand_id"`
	BrandName string  `json:"brand_name" bson:"brand_name"`
	PostCount int     `json:"post_count" bson:"post_count"`
	AvgLikes  float64 `json:"avg_likes" bson:"avg_likes"`
	AvgShares float64 `json:"avg_shares" bson:"avg_shares"`
	Score     int     `json:"score" bson:"score"`
}

// User represents a system user.
type User struct {
	ID           string `json:"id" bson:"_id"`
	Email        string `json:"email" bson:"email"`
	PasswordHash string `json:"-" bson:"password_hash"`
}

// AgentState tracks the current context of the agent loop.
type AgentState struct {
	CurrentBrand BrandProfile
	ActiveTrends []Trend
}
